### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by WeTurkstra** [plug-and-pay/sdk-php#35]
Hi, 

We are thinking about writing an integration into our system.
But one thing is stopping us right now and that is webhooks.

I couldn't find any information regarding webhooks on your website or in this repository. 

Can you confirm that?

Thanks for your time and information.

**Comment by reindert-vetter** [comment]
Good to hear that you want to integrate with us.

We would like to implement the webhooks in a new way. However, I don't expect that to happen in the next 3 months. For now, you can use the old documentation:
https://pp15.docs.apiary.io/#reference/0/helper-collections

**Comment by WeTurkstra** [comment]
Alright thanks. I have have a few more questions :D 

*  How do i set my webhook url?  Is that something i set in the dashboard? 
*  Is there a way to update an order with track and trace information?

Can i have a development account or something to create the integration without having to deal with the 14 days free period?

**Comment by reindert-vetter** [comment]
1. Yes, you can set it in the dashboard:
![image](https://user-images.githubusercontent.com/16726304/217775475-7fb6040e-77b0-4ded-ab2c-cfe22312a74d.png)
If we make the new version for webhooks, it can also be created via the API. As I gather from your post, you want to create it through the API. Is that right?

2. You could do that through comments. For now it is only possible to add comments when creating the order. If you also need to be able to add comments after creating an order, I can discuss internally to add that feature in the coming period.

3. At the moment we do not issue a developer account. You must then indeed take the 14 days free account.

**Comment by WeTurkstra** [comment]
1. Thanks 
2. I only want the orders when they are already created so i can't use that. 
3. Ok, Thank you.

Thanks a lot for taking the time to answer my questions. 
We will discuss internally if its a viable integration for us!

**Comment by reindert-vetter** [comment]
I am now closing this issue. If you have any questions, feel free to reopen it.
